<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net5.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Command\FinancialPortfolio.Services.Orders.Command.Application\FinancialPortfolio.Services.Orders.Command.Application.csproj" />
      <ProjectReference Include="..\..\Query\FinancialPortfolio.Services.Orders.Query.Application\FinancialPortfolio.Services.Orders.Query.Application.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="FinancialPortfolio.Infrastructure" Version="1.5.0" />
      <PackageReference Include="FinancialPortfolio.Messaging.Kafka" Version="1.5.0" />
    </ItemGroup>

</Project>
