<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net5.0</TargetFramework>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Common\FinancialPortfolio.Services.Orders.Infrastructure\FinancialPortfolio.Services.Orders.Infrastructure.csproj" />
      <ProjectReference Include="..\FinancialPortfolio.Services.Orders.Command.Application\FinancialPortfolio.Services.Orders.Command.Application.csproj" />
    </ItemGroup>

    <ItemGroup>
      <None Update="appsettings.json">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="appsettings.Development.json">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="FinancialPortfolio.Infrastructure" Version="2.0.3" />
    </ItemGroup>

</Project>
