<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net5.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Common\FinancialPortfolio.Services.Orders.Domain\FinancialPortfolio.Services.Orders.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="AutoMapper" Version="10.1.1" />
      <PackageReference Include="Grpc.AspNetCore" Version="2.40.0" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="Protos\order.proto" />
      <Protobuf Include="Protos\order.proto" />
    </ItemGroup>

</Project>
