<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net5.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Common\FinancialPortfolio.Services.Orders.Domain\FinancialPortfolio.Services.Orders.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="AutoMapper" Version="11.0.1" />
      <PackageReference Include="FinancialPortfolio.CQRS.Commands" Version="2.0.34" />
      <PackageReference Include="FinancialPortfolio.CQRS.Events" Version="2.0.34" />
      <PackageReference Include="FinancialPortfolio.Messaging" Version="2.0.34" />
      <PackageReference Include="FinancialPortfolio.Shared" Version="2.0.34" />
    </ItemGroup>

</Project>
