<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net5.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Common\FinancialPortfolio.Services.Orders.Domain\FinancialPortfolio.Services.Orders.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="AutoMapper" Version="10.1.1" />
      <PackageReference Include="FinancialPortfolio.CQRS.Commands" Version="1.5.6" />
      <PackageReference Include="FinancialPortfolio.CQRS.Events" Version="1.5.6" />
      <PackageReference Include="FinancialPortfolio.Messaging" Version="1.5.6" />
    </ItemGroup>

</Project>
